#name: PR (main)
#on:
#  pull_request:
#    branches:
#      - main
#  push:
#    branches:
#      - main
#
#jobs:
#  test:
#    name: Run Test Suite [Unit, Instrumented]
#    runs-on: macos-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Set Up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#
#      - name: Execute Unit Tests [./gradlew testDebugUnitTest --stacktrace]
#        run: ./gradlew testDebugUnitTest --stacktrace
#
#      - name: Execute Instrumentation Tests [./gradlew connectedCheck --stacktrace (api 29, x86)]
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          target: default
#          arch: 'x86'
#          profile: Nexus 6
#          script: ./gradlew connectedCheck --stacktrace
#
##  generateArtifacts:
##    name: Generate Debug APK artifacts
##    runs-on: ubuntu-latest
#
##    steps:
##      - uses: actions/checkout@v1
##      - name: set up JDK 1.8
##        uses: actions/setup-java@v1
##        with:
##          java-version: 1.8
##      - name: Build Debug APK [./gradlew assembleDebug --stacktrace]
##        run: ./gradlew assembleDebug --stacktrace
#
##      - name: Upload Debug APK
##        uses: actions/upload-artifact@v1
##        with:
##          name: app-debug-${{ github.run_number }}.apk
##          path: app/build/outputs/apk/debug/app-debug.apk
